sudo: false
language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

env:
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1 TESTS="--show-all"

before_script:
  - phpize && ./configure && make

script:
  - make test | tee tests-output.txt && grep 'TEST SUMMARY$' tests-output.txt > /dev/null ; test $? -ne 0
